"""check de estado en idempotency_keys

Revision ID: 135373233e81
Revises: e5ad238d47ba
Create Date: 2026-08-16 21:27:22.794681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '135373233e81'
down_revision: Union[str, Sequence[str], None] = 'e5ad238d47ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(op.f('ck_idempotency_keys_valid_status'), 'idempotency_keys', "status IN ('pending', 'completed')")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_idempotency_keys_valid_status'), 'idempotency_keys', type_='check')
    # ### end Alembic commands ###
