"""esquema inicial

Revision ID: 27218e9eef3b
Revises: 
Create Date: 2026-08-16 19:57:51.359289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '27218e9eef3b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # citext es extensión "de confianza": no requiere superusuario, solo
    # CREATE en la base. Necesaria antes de crear users.email como CITEXT.
    op.execute("CREATE EXTENSION IF NOT EXISTS citext")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outbox',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('headers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outbox'))
    )
    op.create_index('ix_outbox_unpublished', 'outbox', ['created_at'], unique=False, postgresql_where=sa.text('published_at IS NULL'))
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', postgresql.CITEXT(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'suspended')", name=op.f('ck_users_valid_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('idempotency_keys',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('request_hash', sa.String(), nullable=False),
    sa.Column('response_body', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_idempotency_keys_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_idempotency_keys')),
    sa.UniqueConstraint('user_id', 'key', name='uq_user_idempotency_key')
    )
    op.create_index(op.f('ix_idempotency_keys_user_id'), 'idempotency_keys', ['user_id'], unique=False)
    op.create_table('seed_pairs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('server_seed', sa.LargeBinary(), nullable=False),
    sa.Column('server_seed_hash', sa.String(), nullable=False),
    sa.Column('client_seed', sa.String(), nullable=False),
    sa.Column('nonce', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('revealed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'revealed')", name=op.f('ck_seed_pairs_valid_status')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_seed_pairs_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_seed_pairs'))
    )
    op.create_index(op.f('ix_seed_pairs_user_id'), 'seed_pairs', ['user_id'], unique=False)
    op.create_index('uq_one_active_seed_pair_per_user', 'seed_pairs', ['user_id'], unique=True, postgresql_where=sa.text("status = 'active'"))
    op.create_table('wallets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('balance_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.CheckConstraint('balance_minor >= 0', name=op.f('ck_wallets_balance_non_negative')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_wallets_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wallets')),
    sa.UniqueConstraint('user_id', name=op.f('uq_wallets_user_id'))
    )
    op.create_table('ledger_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('wallet_id', sa.Uuid(), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('balance_after_minor', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('ref_type', sa.String(), nullable=True),
    sa.Column('ref_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('deposit', 'bet_stake', 'bet_payout', 'adjustment')", name=op.f('ck_ledger_entries_valid_kind')),
    sa.CheckConstraint('balance_after_minor >= 0', name=op.f('ck_ledger_entries_balance_after_non_negative')),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], name=op.f('fk_ledger_entries_wallet_id_wallets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ledger_entries'))
    )
    op.create_index(op.f('ix_ledger_entries_wallet_id'), 'ledger_entries', ['wallet_id'], unique=False)
    op.create_table('rounds',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('seed_pair_id', sa.Uuid(), nullable=False),
    sa.Column('nonce', sa.Integer(), nullable=False),
    sa.Column('outcome', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('settled_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'settled')", name=op.f('ck_rounds_valid_status')),
    sa.CheckConstraint('outcome IS NULL OR (outcome >= 0 AND outcome <= 36)', name=op.f('ck_rounds_valid_outcome')),
    sa.ForeignKeyConstraint(['seed_pair_id'], ['seed_pairs.id'], name=op.f('fk_rounds_seed_pair_id_seed_pairs')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_rounds_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rounds')),
    sa.UniqueConstraint('seed_pair_id', 'nonce', name='uq_seed_pair_nonce')
    )
    op.create_index(op.f('ix_rounds_user_id'), 'rounds', ['user_id'], unique=False)
    op.create_table('bets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('round_id', sa.Uuid(), nullable=False),
    sa.Column('bet_type', sa.String(), nullable=False),
    sa.Column('selection', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('stake_minor', sa.BigInteger(), nullable=False),
    sa.Column('payout_minor', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'won', 'lost')", name=op.f('ck_bets_valid_status')),
    sa.CheckConstraint('payout_minor >= 0', name=op.f('ck_bets_non_negative_payout')),
    sa.CheckConstraint('stake_minor > 0', name=op.f('ck_bets_positive_stake')),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], name=op.f('fk_bets_round_id_rounds')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bets'))
    )
    op.create_index(op.f('ix_bets_round_id'), 'bets', ['round_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bets_round_id'), table_name='bets')
    op.drop_table('bets')
    op.drop_index(op.f('ix_rounds_user_id'), table_name='rounds')
    op.drop_table('rounds')
    op.drop_index(op.f('ix_ledger_entries_wallet_id'), table_name='ledger_entries')
    op.drop_table('ledger_entries')
    op.drop_table('wallets')
    op.drop_index('uq_one_active_seed_pair_per_user', table_name='seed_pairs', postgresql_where=sa.text("status = 'active'"))
    op.drop_index(op.f('ix_seed_pairs_user_id'), table_name='seed_pairs')
    op.drop_table('seed_pairs')
    op.drop_index(op.f('ix_idempotency_keys_user_id'), table_name='idempotency_keys')
    op.drop_table('idempotency_keys')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_outbox_unpublished', table_name='outbox', postgresql_where=sa.text('published_at IS NULL'))
    op.drop_table('outbox')
    # ### end Alembic commands ###

    op.execute("DROP EXTENSION IF EXISTS citext")
