"""next_attempt_at en outbox

Revision ID: 4c638e44f315
Revises: 135373233e81
Create Date: 2026-08-16 22:15:24.075809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c638e44f315'
down_revision: Union[str, Sequence[str], None] = '135373233e81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outbox', sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outbox', 'next_attempt_at')
    # ### end Alembic commands ###
